---
- hosts: localhost
  become: true
  vars:
    docker_users:
      - 'vojto'
  tasks:
    - name: Update apt-get repo and cache
      include: tasks/system-update.yml
    - name: Upgrade all apt packages
      include: tasks/system-upgrade.yml  
    - name: install dependecies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: add GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present
    - name: install docker
      apt:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose
    - name: make sure docker is on
      service:
        name: docker
        state: started
        enabled: yes
    - name: adding docker users (for use without sudo)
      user:
        name: "{{ item }}"
        append: yes
        groups: docker
      become: true
      with_items:  '{{ docker_users }}'
  handlers:
    - name: restart docker
      service: 
        name: docker 
        state: restarted

# doplnit do .bashrc startovanie dockerd daemona