---
- hosts: localhost
  gather_facts: no
  tasks:
    - name: Getting images name
      include: tasks/docker-container-get-names.yml 
    - name: Stoping images
      include: tasks/docker-container-stop.yml
